name: Atualizar Estatísticas do README

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Baixar estatísticas do GitHub
        run: |
          curl -o github-stats.png "https://github-readme-stats.vercel.app/api?username=xpedrotx&show_icons=true&theme=transparent&include_all_commits=true&locale=pt-br"
          curl -o github-langs.png "https://github-readme-stats.vercel.app/api/top-langs/?username=xpedrotx&theme=transparent&layout=compact&custom_title=Tecnologias&langs_count=9"

      - name: Commit e push das alterações
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md github-stats.png github-langs.png
          git commit -m "Atualizando estatísticas do README" || echo "Nada para atualizar"
          git push https://xpedrotx:${{ secrets.GH_PAT }}@github.com/xpedrotx/xpedrotx.git main
