name: Atualizar Estatísticas do README

on:
  schedule:
    - cron: "0 * * * *" # Executa a cada hora
  workflow_dispatch: # Permite execução manual

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Atualizar estatísticas
        uses: anuraghazra/github-readme-stats@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit e push das alterações
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Atualizando estatísticas do README" || echo "Nada para atualizar"
          git push
